# Generated by Django 6.0 on 2025-12-18 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_bac', models.CharField(choices=[('S', 'Série S (Scientifique)'), ('C', 'Série C'), ('D', 'Série D'), ('A1', 'Série A1'), ('L', 'Série L (Littéraire)'), ('OSE', 'Série OSE')], max_length=10)),
                ('releve_note', models.ImageField(upload_to='releves_notes/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('initial', 'Information initiale envoyée'), ('questions_sent', "Questions envoyées à l'utilisateur"), ('completed', 'Orientation complétée'), ('error', 'Erreur')], default='initial', max_length=20)),
                ('questions_json', models.TextField(blank=True, help_text='Questions au format JSON', null=True)),
                ('reponses_json', models.TextField(blank=True, help_text='Réponses au format JSON', null=True)),
                ('filieres_recommandees_json', models.TextField(blank=True, help_text='Filières recommandées au format JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'Orientation",
                'verbose_name_plural': "Sessions d'Orientation",
                'ordering': ['-created_at'],
            },
        ),
    ]
